version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      DB_HOST: lucky-game-app_mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: lucky-game-app_redis
    ports:
      - "9000:9000"
    depends_on:
      - lucky-game-app_mysql
      - lucky-game-app_redis

  lucky-game-app_nginx_nginx:
    image: nginx:stable-alpine
    container_name: lucky-game-app_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  lucky-game-app_mysql:
    image: mysql:8.0
    container_name: lucky-game-app_mysql
    ports:
      - "8800:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql_data:/var/lib/mysql

  lucky-game-app_redis:
    image: redis:alpine
    container_name: lucky-game-app_redis
    ports:
      - "6381:6379"

volumes:
  mysql_data:
